### ISSUE TITLE
Use .env file for hydra configuration rather than modifying the docker-compose.yml file

### ISSUE THREAD

**Issue by manueldelreal** [reactioncommerce/reaction-hydra#14]
# Feature Name
Configuration via .env file

### Summary description
It will be beneficial to be able to set the OAUTH variables via a .env file rather than hardcoding the docker-compose.yml configuration. 

### Rationale for why this feature is necessary
Right now I'm testing via a remote server but I can't login or create accounts because the default OAUTH values are hardcoded to `localhost` so I'm modifying `docker-compose.yml` to work around this, e.g. server address is `http://52.214.240.50:4000/` but when I hit sign in or create account browser goes to `http://localhost:4444/oauth2/auth?loginAction=signin&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&scope=offline&state=SQxmgrJ7QxtDlvHVBjGJpiA7&client_id=reaction-next-starterkit` which results in a browser error

**Comment by impactmass** [comment]
closed in #15
