### ISSUE TITLE
Update hydra to v1.0.0+oryOS.12

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction-hydra#21]
### Summary description
The docker compose-file is still using the image `hydra:v1.0.0-beta.9-alpine`. from September last year.
Version 1.0.0 has been released 16 days ago.

### Rationale for why this feature is necessary
Several versions have been released then with a lot of bugfixes and increased stability.

**Comment by loan-laux** [comment]
Any plan of using a stable 1.x version soon-ish?

**Comment by spencern** [comment]
We'll update to this version alongside our v3.0.0 release of Reaction. There are some breaking changes associated with the update.
