### ISSUE TITLE
The v2.8.0 release has a typo in the tag name

### ISSUE THREAD

**Issue by jackson-sandland** [reactioncommerce/reaction-hydra#33]
The `v2.8.0` release's corresponding tag is named `v.2.8.0` not `v2.8.0`. 
The makefile in the `reaction-platform` repo tries to checkout the `v2.8.0` `reaction-hydra` release but it doesn't exist so an error is thrown when running `make`.

The `v2.8.0` release tag should be renamed to `v2.8.0` to resolve the error in the `reaction-platform` installation.

**Comment by machikoyasuda** [comment]
We've updated this: https://github.com/reactioncommerce/reaction-hydra/releases/tag/v2.8.0

Thank you so much for pointing this out!
