### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-hydra#36]
# Feature Name
I'd like for us to rename this repo to either `reaction-authentication` or simply `authentication`.

**Comment by focusaurus** [comment]
I believe we're mostly agreed to not use "reaction-" prefixes anymore (well at least @ticean and I).

**Comment by nnnnat** [comment]
I'm also in that camp as well as @rosshadden. Lets go with `authentication` then

**Comment by ticean** [comment]
Hmm.. not sure `authentication` is the right name because Hydra's not providing authentication. Maybe @mpaktiti can help us with the right suggestion?

**Comment by mpaktiti** [comment]
Hydra is an Authorization Server so I'd go with something like that (`authorization`, or `authorization-server`, or `authz-server`)

**Comment by agustif** [comment]
What about going monorepo and using the umbrella @reactioncommerce like I sugggested here
https://github.com/reactioncommerce/reaction-feature-requests/issues/122
with subfolders/for-packages

Something like @reactioncommerce/auth or /authentication for example
