### ISSUE TITLE
[DOCS] Outdated link and/or documentation

### ISSUE THREAD

**Issue by maarteNNNN** [reactioncommerce/reaction-hydra#50]
Type: **minor**

**Describe the bug**
Following the documentation of version `3.6.0` I encountered a sample client creation script. This however contains a broken link. Looking inside the repo this script doesn't exist anymore.

**To Reproduce**
[Link](https://docs.reactioncommerce.com/docs/understanding-hydra-auth-setup#setting-up-the-client)

**Expected behavior**
Should work or be explained better what the steps to creating a client are.

**Version**
 - Version of Reaction docs `3.6.0`

**Comment by aldeed** [comment]
@maarteNNNN The page you link to does not actually "exist" but you're encountering [a bug](https://github.com/facebook/docusaurus/issues/2429) in the docs builder software we use (Docusaurus) where articles that have been removed can still be found through search. (A good clue you're on an old page that shouldn't exist is that the sidebar disappears.)

The actual current version of that article is here: https://docs.reactioncommerce.com/docs/developer-authentication
