### ISSUE TITLE
Add installation / configuration / deployment and related docs

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction-hydra#6]
- Explain rationale for OAuth2, and a new token service
- Docs or link to docs for the OAuth2/OIDC flows that we use
  - For user unfamiliar with OAuth2/OIDC
- Migration Guide
  - Generally explains what’s needed to migrate from 1.x (any data migration?)
  - Configuration guide
    - New configuration settings are required!
- Production Deployment Guide
  - Standup Hydra
  - DB as a service / SQL DB
  - Tooling to create secure clients for production? (2.x)
- Troubleshooting Guide

Part of reactioncommerce/reaction#4618

**Comment by aldeed** [comment]
We should document this in https://docs.reactioncommerce.com/docs/next/intro instead of readme.

Developer docs in "Getting Started as a Developer" section.
Deployment docs in "System Administrator's Guide" section.

Then a link in the hydra readme to those public docs
